#端口号
server:
  port: 8000

#数据库配置
spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: 123456
    #连接accesss
    slave:
      driver-class-name: net.ucanaccess.jdbc.UcanaccessDriver
      jdbc-url: jdbc:ucanaccess://D:/cpc/cpms.mdb;openExclusive=false;ignoreCase=true
      username: Admin
      password: admin
  #配置activemq
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    close-timeout: 15s # 在考虑结束之前等待的时间
    in-memory: true # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值
    non-blocking-redelivery: false # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留
    send-timeout: 0 # 等待消息发送响应的时间。设置为0等待永远。
    queue-name: active.queue
    topic-name: active.topic.name.model
    pool:
      enabled: true
      max-connections: 10 #连接池最大连接数
      idle-timeout: 30000 #空闲的连接过期时间，默认为30秒
    packages:
      trust-all: true
#配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

